<?php
namespace tests\app\decibel\debug;

use app\decibel\debug\DDebuggingInformation;
use app\decibel\test\DTestCase;

class TestDebuggingInformation extends DDebuggingInformation
{
}

/**
 * Test class for DDebuggingInformation.
 * Generated by Decibel on 2011-10-31 at 14:08:49.
 */
class DDebuggingInformationTest extends DTestCase
{
    /**
     * @covers app\decibel\debug\DDebuggingInformation::getFile
     * @covers app\decibel\debug\DDebuggingInformation::setFile
     */
    public function testsetFile()
    {
        $info = new TestDebuggingInformation();
        $this->assertSame($info, $info->setFile('file'));
        $this->assertSame('file', $info->getFile());
        $this->assertSame($info, $info->setFile(null));
        $this->assertNull($info->getFile());
    }

    /**
     * @covers app\decibel\debug\DDebuggingInformation::getLine
     * @covers app\decibel\debug\DDebuggingInformation::setLine
     */
    public function testsetLine()
    {
        $info = new TestDebuggingInformation();
        $this->assertSame($info, $info->setLine(100));
        $this->assertSame(100, $info->getLine());
        $this->assertSame($info, $info->setLine(null));
        $this->assertNull($info->getLine());
    }

    /**
     * @covers app\decibel\debug\DDebuggingInformation::getMessage
     * @covers app\decibel\debug\DDebuggingInformation::setMessage
     */
    public function testsetMessage()
    {
        $info = new TestDebuggingInformation();
        $this->assertSame($info, $info->setMessage('message'));
        $this->assertSame('message', $info->getMessage());
    }

    /**
     * @covers app\decibel\debug\DDebuggingInformation::getBacktrace
     * @covers app\decibel\debug\DDebuggingInformation::setBacktrace
     */
    public function testsetBacktrace()
    {
        $info = new TestDebuggingInformation();
        $this->assertSame($info, $info->setBacktrace('backtrace'));
        $this->assertSame('backtrace', $info->getBacktrace());
    }
}
