<?php
namespace tests\app\decibel\debug;

use app\decibel\test\DTestCase;

/**
 * Test class for DException.
 * Generated by Decibel on 2011-10-31 at 14:08:49.
 */
class DExceptionTest extends DTestCase
{
    /**
     * @covers app\decibel\debug\DException::__construct
     */
    public function testExceptionMessage()
    {
        // Untestabled due to the pattern of implementation.
        //		$mock = $this->getMockForAbstractClass(
        //			'app\\decibel\\debug\\DException',
        //			array(
        //				'information'	=> array(),
        //			)
        //		);
    }
}
