<?php
namespace tests\app\decibel\debug;

use app\decibel\authorise\DGuestUser;
use app\decibel\authorise\DRootUser;
use app\decibel\configuration\DApplicationMode;
use app\decibel\debug\DGetDebugConsole;
use app\decibel\test\DTestCase;

/**
 * Test class for DGetDebugConsole.
 * Generated by Decibel on 2011-10-31 at 14:08:52.
 */
class DGetDebugConsoleTest extends DTestCase
{
    /**
     * @covers app\decibel\debug\DGetDebugConsole::authorise
     */
    public function testauthorise()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $rpc = DGetDebugConsole::loadWithoutParameters();
        $guest = DGuestUser::create();
        $root = DRootUser::create();
        $rpc->setFieldValue('ignoreMode', true);
        $this->assertTrue($rpc->authorise($guest));
        $this->assertTrue($rpc->authorise($root));
        $rpc->setFieldValue('ignoreMode', false);
        DApplicationMode::setMode(DApplicationMode::MODE_DEBUG);
        $this->assertTrue($rpc->authorise($guest));
        $this->assertTrue($rpc->authorise($root));
        DApplicationMode::setMode(DApplicationMode::MODE_PRODUCTION);
        $this->assertTrue($rpc->authorise($guest));
        $this->assertTrue($rpc->authorise($root));
    }

    /**
     * @covers app\decibel\debug\DGetDebugConsole::getResultType
     */
    public function testgetResultType()
    {
        $rpc = DGetDebugConsole::loadWithoutParameters();
        $this->assertSame('text/html', $rpc->getResultType());
    }

    /**
     * @covers app\decibel\debug\DGetDebugConsole::profile
     */
    public function testprofile()
    {
        $rpc = DGetDebugConsole::loadWithoutParameters();
        $this->assertFalse($rpc->profile());
    }

    /**
     * @covers app\decibel\debug\DGetDebugConsole::execute
     */
    public function testexecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
