<?php
namespace tests\app\decibel\debug;

use app\decibel\debug\DOnProfilerReport;
use app\decibel\test\DTestCase;

/**
 * Test class for DOnProfilerReport.
 * Generated by Decibel on 2012-04-12 at 09:08:13.
 */
class DOnProfilerReportTest extends DTestCase
{
    /**
     * @covers app\decibel\debug\DOnProfilerReport::define
     */
    public function testdefine()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $event = new DOnProfilerReport();
        $this->assertSame(array(), $event->getFields());
    }

    /**
     * @covers app\decibel\debug\DOnProfilerReport::getDescription
     */
    public function testgetDescription()
    {
        $this->assertNull(DOnProfilerReport::getDescription());
    }

    /**
     * @covers app\decibel\debug\DOnProfilerReport::getDisplayName
     */
    public function testgetDisplayName()
    {
        $this->assertNull(DOnProfilerReport::getDisplayName());
    }
}
