<?php
namespace tests\app\decibel\model;

use app\decibel\test\DTestCase;

/**
 * Test class for DBaseModel_Definition.
 * Generated by Decibel on 2012-04-12 at 09:08:42.
 */
class DBaseModel_DefinitionTest extends DTestCase
{
    /**
     * @covers {className}::{origMethodName}
     * @todo Implement test__sleep().
     */
    public function test__sleep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetCurrentDate().
     */
    public function testGetCurrentDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetCurrentTimestamp().
     */
    public function testGetCurrentTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testIsInstanceOf().
     */
    public function testIsInstanceOf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testSetEventHandler().
     */
    public function testSetEventHandler()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
