<?php
namespace tests\app\decibel\model;

use app\decibel\model\DLightModel;
use app\decibel\model\DLightModel_Definition;
use app\decibel\model\field\DTextField;
use app\decibel\test\DTestCase;

abstract class TestAbstractLightModel extends DLightModel
{
}

class TestLightModel extends DLightModel
{
    public static function getDisplayName()
    {
        return 'Test Light Model';
    }

    public static function getDisplayNamePlural()
    {
        return 'Test Light Models';
    }

    protected function getStringValue()
    {
        return $this->getFieldValue('title');
    }
}

class TestLightModel_Definition extends DLightModel_Definition
{
    public function __construct($qualifiedName)
    {
        parent::__construct($qualifiedName);
        $title = new DTextField('title', 'Title');
        $this->addField($title);
    }
}

/**
 * Test class for DLightModel.
 * Generated by Decibel on 2012-04-12 at 09:08:44.
 */
class DLightModelTest extends DTestCase
{
    /**
     * @covers app\decibel\model\DLightModel::create
     */
    public function testcreate()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $model = TestLightModel::create();
        $this->assertInstanceOf('tests\\app\\decibel\\model\\TestLightModel', $model);
    }

    /**
     * @covers app\decibel\model\DLightModel::create
     */
    public function testcreate_nonNumericId()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $model = TestLightModel::create('test');
        $this->assertNull($model);
    }

    /**
     * @covers app\decibel\model\DLightModel::create
     */
    public function testcreate_invalidId()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $model = TestLightModel::create(1);
        $this->assertNull($model);
    }

    /**
     * @covers app\decibel\model\DLightModel::create
     * @expectedException app\decibel\model\debug\DUnknownModelInstanceException
     * @todo   Can't currently test this as above classes not in the registry...
     */
    public function xtestcreate_abstract()
    {
        TestAbstractLightModel::create(0);
    }

    /**
     * @covers app\decibel\model\DLightModel::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\DLightModel::__get
     * @todo   Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\DLightModel::__set
     * @todo   Implement test__set().
     */
    public function test__set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\DLightModel::cleanDatabase
     * @todo   Implement testcleanDatabase().
     */
    public function testcleanDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\DLightModel::getStringValueFieldName
     */
    public function testgetStringValueFieldName()
    {
        $this->assertSame(DLightModel::FIELD_STRING_VALUE, DLightModel::getStringValueFieldName());
    }

    /**
     * @covers app\decibel\model\DLightModel::delete
     * @todo   Implement testdelete().
     */
    public function testdelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\DLightModel::save
     * @todo   Implement testSave().
     */
    public function testsave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\DLightModel::search
     */
    public function testsearch()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $search = TestLightModel::search();
        $this->assertInstanceOf('app\\decibel\\model\\search\\DLightModelSearch', $search);
        $this->assertSame('tests\\app\\decibel\\model\\TestLightModel', $search->qualifiedName);
    }

    /**
     * @covers app\decibel\model\DLightModel::link
     */
    public function testlink()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $link = TestLightModel::link();
        $this->assertInstanceOf('app\\decibel\\model\\search\\DLightModelSearch', $link);
        $this->assertSame('tests\\app\\decibel\\model\\TestLightModel', $link->qualifiedName);
    }
}
