<?php
namespace tests\app\decibel\health;

use app\decibel\health\DHealthCheckResult;
use app\decibel\test\DTestCase;

/**
 * Test class for DHealthCheckResult.
 * Generated by Decibel on 2012-04-12 at 09:54:12.
 */
class DHealthCheckResultTest extends DTestCase
{
    /**
     * @covers app\decibel\health\DHealthCheckResult::__construct
     */
    public function testConstruct()
    {
        $check = new DHealthCheckResult(
            DHealthCheckResult::HEALTH_CHECK_MESSAGE,
            'Test',
            array(),
            'http://www.test.com'
        );
        $this->assertInstanceOf('app\decibel\health\DHealthCheckResult', $check);
        $this->assertSame('Test', $check->getDescription());
        $this->assertSame(md5(DHealthCheckResult::HEALTH_CHECK_MESSAGE . 'Test'), $check->getId());
        $this->assertSame('http://www.test.com', $check->getRepairLink());
        $this->assertSame(DHealthCheckResult::HEALTH_CHECK_MESSAGE, $check->getType());
    }

    /**
     * @covers app\decibel\health\DHealthCheckResult::getDescription
     */
    public function testDescription()
    {
        $check = new DHealthCheckResult(
            DHealthCheckResult::HEALTH_CHECK_MESSAGE,
            'Test'
        );
        $this->assertSame('Test', $check->getDescription());
    }

    /**
     * @covers app\decibel\health\DHealthCheckResult::getId
     */
    public function testgetId()
    {
        $check = new DHealthCheckResult(
            DHealthCheckResult::HEALTH_CHECK_MESSAGE,
            'Test'
        );
        $this->assertSame(md5(DHealthCheckResult::HEALTH_CHECK_MESSAGE . 'Test'), $check->getId());
    }

    /**
     * @covers app\decibel\health\DHealthCheckResult::getRepairLink
     */
    public function testgetRepairLink()
    {
        $check = new DHealthCheckResult(
            DHealthCheckResult::HEALTH_CHECK_MESSAGE,
            'Test',
            array(),
            'http://test.com'
        );
        $this->assertSame('http://test.com', $check->getRepairLink());
        $check = new DHealthCheckResult(
            DHealthCheckResult::HEALTH_CHECK_MESSAGE,
            'Test',
            array()
        );
        $this->assertEmpty($check->getRepairLink());
    }

    /**
     * @covers app\decibel\health\DHealthCheckResult::getType
     */
    public function testgetType()
    {
        $check = new DHealthCheckResult(
            DHealthCheckResult::HEALTH_CHECK_MESSAGE,
            'Test'
        );
        $this->assertSame(DHealthCheckResult::HEALTH_CHECK_MESSAGE, $check->getType());
    }
}
