<?php
namespace tests\app\decibel\health;

use app\decibel\authorise\DGuestUser;
use app\decibel\authorise\DRootUser;
use app\decibel\health\DHealthCheck;
use app\decibel\test\DTestCase;

class TestHealthCheck extends DHealthCheck
{
    public function checkHealth()
    {
    }

    public function getComponentName()
    {
    }
}

/**
 * Test class for DHealthCheck.
 * Generated by Decibel on 2012-04-12 at 09:54:12.
 */
class DHealthCheckTest extends DTestCase
{
    /**
     * @covers app\decibel\health\DHealthCheck::load
     */
    public function test__construct()
    {
        $check = TestHealthCheck::load();
        $this->assertInstanceOf('app\\decibel\\health\\DHealthCheck', $check);
    }
}
