<?php
namespace tests\app\decibel\auditing;

use app\decibel\auditing\DAuditSearch;
use app\decibel\test\DTestCase;

/**
 * Test class for DAuditSearch.
 * Generated by Decibel on 2012-04-12 at 09:53:58.
 */
class DAuditSearchTest extends DTestCase
{
    /**
     * @covers app\decibel\auditing\DAuditSearch::__construct
     * @todo   Implement test__construct().
     */
    public function test__construct()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $search = new DAuditSearch('tests\app\decibel\auditing\TestAuditRecord');
        $this->assertInstanceOf('app\\decibel\\auditing\\DAuditSearch', $search);
        $this->assertInstanceOf('tests\app\decibel\auditing\TestAuditRecord', $search->definition);
        $this->assertSame('tests\app\decibel\auditing\TestAuditRecord', $search->qualifiedName);
        $this->assertSame('tests_decibel_auditing_testauditrecord', $search->tableName);
    }

    /**
     * @covers app\decibel\auditing\DAuditSearch::getObjects
     * @expectedException app\decibel\model\debug\DInvalidSearchException
     */
    public function testgetObjects()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $search = new DAuditSearch('tests\app\decibel\auditing\TestAuditRecord');
        $search->getObjects();
    }

    /**
     * @covers app\decibel\auditing\DAuditSearch::getObject
     * @expectedException app\decibel\model\debug\DInvalidSearchException
     */
    public function testgetObject()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $search = new DAuditSearch('tests\app\decibel\auditing\TestAuditRecord');
        $search->getObject();
    }
}
