<?php
namespace tests\app\decibel\database\schema;

use app\decibel\database\schema\DIndexDefinition;
use app\decibel\test\DTestCase;
use DOMDocument;

/**
 * Test class for DIndexDefinition.
 * Generated by Decibel on 2011-10-31 at 14:07:56.
 */
class DIndexDefinitionTest extends DTestCase
{
    /**
     * @covers app\decibel\database\schema\DIndexDefinition::createFromDIndex
     * @todo   Implement testcreateFromDIndex().
     */
    public function testcreateFromDIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\database\schema\DIndexDefinition::compareWith
     * @todo   Implement testcompareWith().
     */
    public function testcompareWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\database\schema\DIndexDefinition::setName
     * @covers app\decibel\database\schema\DIndexDefinition::getName
     */
    public function testsetName()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $index = new DIndexDefinition('test', 'type', array('field1', 'field2'));
        $this->assertSame($index, $index->setName('name'));
        $this->assertSame('name', $index->getName());
    }

    /**
     * @covers app\decibel\database\schema\DIndexDefinition::setType
     * @covers app\decibel\database\schema\DIndexDefinition::getType
     */
    public function testsetType()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $index = new DIndexDefinition('test', 'type', array('field1', 'field2'));
        $this->assertSame($index, $index->setType('name'));
        $this->assertSame('name', $index->getType());
    }

    /**
     * @covers app\decibel\database\schema\DIndexDefinition::setColumns
     * @covers app\decibel\database\schema\DIndexDefinition::getColumns
     */
    public function testsetFields()
    {
        $index = new DIndexDefinition('test', 'type', array('field1', 'field2'));
        $this->assertSame($index, $index->setColumns(array('field3', 'field4')));
        $this->assertSame(array('field3', 'field4'), $index->getColumns());
    }
}
