<?php
namespace tests\app\decibel\database\schema;

use app\decibel\database\schema\DColumnDefinition;
use app\decibel\database\schema\DIndexDefinition;
use app\decibel\database\schema\DTableDefinition;
use app\decibel\stream\DFileStream;
use app\decibel\test\DTestCase;
use app\decibel\xml\DXPath;
use DOMDocument;

/**
 * Test class for DTableDefinition.
 * Generated by Decibel on 2011-10-31 at 14:08:35.
 */
class DTableDefinitionTest extends DTestCase
{
    /**
     * @covers app\decibel\database\schema\DTableDefinition::addColumn
     * @covers app\decibel\database\schema\DTableDefinition::getColumn
     */
    public function testaddColumn()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $table = new DTableDefinition('test');
        $column = new DColumnDefinition('test');
        $table->addColumn($column);
        $this->assertSame($table, $column->getTable());
        $this->assertSame($column, $table->getColumn($column->getName()));
    }

    /**
     * @covers app\decibel\database\schema\DTableDefinition::addColumns
     * @covers app\decibel\database\schema\DTableDefinition::getColumns
     */
    public function testaddColumns()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $table = new DTableDefinition('test');
        $column1 = new DColumnDefinition('test');
        $column2 = new DColumnDefinition('test2');
        $columns = array();
        $columns[] = $column1;
        $columns[] = $column2;
        $table->addColumns($columns);
        $this->assertSame(
            array(
                'test'  => $column1,
                'test2' => $column2,
            ),
            $table->getColumns()
        );
    }

    /**
     * @covers app\decibel\database\schema\DTableDefinition::addIndex
     * @covers app\decibel\database\schema\DTableDefinition::getIndexes
     */
    public function testaddIndex()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $table = new DTableDefinition('test');
        $indexes = array();
        $index1 = new DIndexDefinition('test', 'type', array('field1', 'field2'));
        $index1->setTable($table);
        $indexes['test'] = $index1;
        $table->addIndexes($indexes);
        $this->assertSame($indexes, $table->getIndexes());
    }

    /**
     * @covers app\decibel\database\schema\DTableDefinition::hasColumn
     */
    public function testhasColumn()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $table = new DTableDefinition('test');
        $column = new DColumnDefinition('column1');
        $table->addColumn($column);
        $this->assertTrue($table->hasColumn($column));
    }
}
