<?php
namespace tests\app\decibel\database\statement;

use app\decibel\database\statement\DLeftJoin;
use app\decibel\test\DTestCase;

/**
 * Test class for DLeftJoin.
 * Generated by Decibel on 2011-10-31 at 14:08:10.
 */
class DLeftJoinTest extends DTestCase
{
    /**
     * @var DLeftJoin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DLeftJoin('MyTable', 'test1');
    }

    /**
     * @covers app\decibel\database\statement\DLeftJoin::__toString
     */
    public function test__toString()
    {
        $result = $this->object;
        $this->assertInternalType('object', $result);
        $this->assertSame(' LEFT JOIN `MyTable` ON test1', (string)$result);
    }
}
