<?php
namespace tests\app\decibel\model\search;

use app\decibel\model\search\DAndCondition;
use app\decibel\test\DTestCase;

/**
 * Test class for DAndCondition.
 * Generated by Decibel on 2012-04-12 at 09:08:49.
 */
class DAndConditionTest extends DTestCase
{
    /**
     * @covers app\decibel\model\search\DAndCondition::__construct
     * @covers app\decibel\model\search\DAndCondition::hasConditions
     */
    public function test__construct_blank()
    {
        $condition = new DAndCondition();
        $this->assertInstanceOf('app\\decibel\\model\\search\\DAndCondition', $condition);
        $this->assertFalse($condition->hasConditions());
    }

    /**
     * @covers app\decibel\model\search\DAndCondition::__construct
     * @covers app\decibel\model\search\DAndCondition::hasConditions
     */
    public function test__construct_conditions()
    {
        $condition = new DAndCondition(
            new DAndCondition(),
            new DAndCondition()
        );
        $this->assertInstanceOf('app\\decibel\\model\\search\\DAndCondition', $condition);
        $this->assertTrue($condition->hasConditions());
    }

    /**
     * @covers app\decibel\model\search\DAndCondition::addCondition
     * @covers app\decibel\model\search\DAndCondition::hasConditions
     */
    public function testaddCondition()
    {
        $condition = new DAndCondition();
        $this->assertFalse($condition->hasConditions());
        $this->assertSame($condition, $condition->addCondition(new DAndCondition()));
        $this->assertTrue($condition->hasConditions());
    }
}
