<?php
namespace tests\app\decibel\model\search;

use app\decibel\test\DTestCase;

/**
 * Test class for DModelSearch.
 * Generated by Decibel on 2011-10-31 at 14:11:18.
 */
class DModelSearchTest extends DTestCase
{
    /**
     * @covers app\decibel\model\search\DModelSearch::__construct
     * @todo   Implement test__construct().
     */
    public function test__construct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::__sleep
     * @todo   Implement test__sleep().
     */
    public function test__sleep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::applyDefaultGroup
     * @todo   Implement testapplyDefaultGroup().
     */
    public function testapplyDefaultGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::removeDefaultFilters
     * @todo   Implement testremoveDefaultFilters().
     */
    public function testremoveDefaultFilters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::filterByChildField
     * @todo   Implement testfilterByChildField().
     */
    public function testfilterByChildField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::filterByField
     * @todo   Implement testfilterByField().
     */
    public function testfilterByField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::requirePermission
     * @todo   Implement testrequirePermission().
     */
    public function testrequirePermission()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::getRelatedObjects
     * @todo   Implement testgetRelatedObjects().
     */
    public function testgetRelatedObjects()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::getRelatedIds
     * @todo   Implement testgetRelatedIds().
     */
    public function testgetRelatedIds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::prepare
     * @todo   Implement testprepare().
     */
    public function testprepare()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::checkPermissions
     * @todo   Implement testcheckPermissions().
     */
    public function testcheckPermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::checkPermissionForId
     * @todo   Implement testcheckPermissionForId().
     */
    public function testcheckPermissionForId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::filterByTaxonomy
     * @todo   Implement testfilterByTaxonomy().
     */
    public function testfilterByTaxonomy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::getPermissonTemplates
     * @todo   Implement testgetPermissonTemplates().
     */
    public function testgetPermissonTemplates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::getPermissionInheritees
     * @todo   Implement testgetPermissionInheritees().
     */
    public function testgetPermissionInheritees()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::getValidIds
     * @todo   Implement testgetValidIds().
     */
    public function testgetValidIds()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\model\search\DModelSearch::executeSearch
     * @todo   Implement testexecuteSearch().
     */
    public function testexecuteSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
