<?php
namespace tests\app\decibel\utility;

use app\decibel\test\DTestCase;

/**
 * Test class for DBaseClass.
 * Generated by Decibel on 2011-10-31 at 14:13:27.
 */
class DBaseClassTest extends DTestCase
{
    /**
     * @covers app\decibel\utility\DBaseClass::__call
     * @expectedException app\decibel\debug\DInvalidMethodException
     */
    public function test__call()
    {
        $baseClass = $this->getObjectForTrait('app\\decibel\\utility\\DBaseClass');
        $baseClass->aMethod();
    }

    /**
     * @covers app\decibel\utility\DBaseClass::__get
     * @expectedException app\decibel\debug\DInvalidPropertyException
     */
    public function test__get()
    {
        $baseClass = $this->getObjectForTrait('app\\decibel\\utility\\DBaseClass');
        $baseClass->aProperty;
    }

    /**
     * @covers app\decibel\utility\DBaseClass::__set
     * @expectedException app\decibel\debug\DInvalidPropertyException
     */
    public function test__set()
    {
        $baseClass = $this->getObjectForTrait('app\\decibel\\utility\\DBaseClass');
        $baseClass->aProperty = true;
    }
}
