<?php
namespace tests\app\decibel\event;

use app\decibel\event\DEventSubscription;
use app\decibel\test\DTestCase;

/**
 * Test class for DEventSubscription.
 * Generated by Decibel on 2011-10-31 at 14:08:29.
 */
class DEventSubscriptionTest extends DTestCase
{
    /**
     * @covers app\decibel\event\DEventSubscription::__construct
     * @covers app\decibel\event\DEventSubscription::getObserver
     * @covers app\decibel\event\DEventSubscription::getEventData
     */
    public function test__construct()
    {
        $subscription = new DEventSubscription('debug', 'eventData');
        $this->assertInstanceOf('app\\decibel\\event\\DEventSubscription', $subscription);
        $this->assertSame('debug', $subscription->getObserver());
        $this->assertSame('eventData', $subscription->getEventData());
    }

    /**
     * @covers app\decibel\event\DEventSubscription::__construct
     * @expectedException app\decibel\event\debug\DInvalidObserverException
     */
    public function test__construct_invalidCallable()
    {
        new DEventSubscription(array('invalid', 'callable'));
    }
}
