<?php
namespace tests\app\decibel\event;

use app\decibel\debug\DOnErrorHandled;
use app\decibel\event\DEventReflection;
use app\decibel\test\DTestCase;

/**
 * Test class for DEventReflection.
 * Generated by Decibel on 2011-10-31 at 14:08:29.
 */
class DEventReflectionTest extends DTestCase
{
    /**
     * @covers app\decibel\event\DEventReflection::__construct
     */
    public function test__construct()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $reflection = new DEventReflection(DOnErrorHandled::class);
        $this->assertInstanceOf(DEventReflection::class, $reflection);

        $event = new DOnErrorHandled();
        $this->assertSame($event->getFields(), $reflection->getFields());
    }
}
