<?php
use app\decibel\authorise\DPrivilege;
use app\decibel\test\DTestCase;

/**
 * Test class for DPrivilege.
 * Generated by Decibel on 2011-10-31 at 14:06:38.
 */
class DPrivilegeTest extends DTestCase
{
    /**
     * @covers app\decibel\authorise\DPrivilege::getName
     */
    public function testGetName()
    {
        $privilege = new DPrivilege('root-canDo');
        $this->assertSame('root-canDo', $privilege->getName());
    }

    /**
     * @covers app\decibel\authorise\DPrivilege::getGroup
     */
    public function testGetGroup()
    {
        $privilege = new DPrivilege(uniqid(), 'www');
        $this->assertSame('www', $privilege->getGroup());
    }

    /**
     * @covers app\decibel\authorise\DPrivilege::getDescription
     */
    public function testGetDescription()
    {
        $privilege = new DPrivilege(uniqid(), 'www', 'A group description');
        $this->assertSame('A group description', $privilege->getDescription());
    }

    /**
     * @covers app\decibel\authorise\DPrivilege::__tostring
     */
    public function testToString()
    {
        $privilege = new DPrivilege('root-canDo');
        $this->assertSame('root-canDo', $privilege->getName());
        $this->assertSame('root-canDo', (string) $privilege);
    }

    public function testGetPrivilegeInformation()
    {
        // empty
    }

    /**
     * @covers app\decibel\authorise\DPrivilege::isValid
     */
    public function testIsValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\authorise\DPrivilege::registerMissingPrivileges
     */
    public function testRegisterMissingPrivileges()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\authorise\DPrivilege::registerPrivilege
     */
    public function testRegisterPrivilege()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\authorise\DPrivilege::{origMethodName}
     */
    public function testGetPrivilegeNames()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
