<?php
namespace tests\app\decibel\router;

use app\decibel\router\DRpcRouter;
use app\decibel\test\DTestCase;

class TestRpcRouter extends DRpcRouter
{
    public function testGetErrorMessage($uri)
    {
        return $this->getErrorMessage($uri);
    }

    public function testUriToQualifiedName($uri)
    {
        return $this->uriToQualifiedName($uri);
    }
}

/**
 * Test class for DRpcRouter.
 * Generated by Decibel on 2011-10-31 at 14:12:38.
 */
class DRpcRouterTest extends DTestCase
{
    /**
     * @covers app\decibel\router\DRpcRouter::uriToQualifiedName
     */
    public function testuriToQualifiedName()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $router = TestRpcRouter::load();
        $this->assertSame(
            'app\\MyApp\\MyNamespace\\MyRpc',
            $router->testUriToQualifiedName('remote/MyApp/MyNamespace/MyRpc')
        );
        $this->assertSame(
            'app\\MyApp\\MyNamespace\\MyRpc',
            $router->testUriToQualifiedName('remote/MyApp/MyNamespace/MyRpc/')
        );
        $this->assertSame(
            'app\\MyApp\\MyNamespace\\MyRpc',
            $router->testUriToQualifiedName('/remote/MyApp/MyNamespace/MyRpc/')
        );
        $this->assertSame(
            'app\\MyApp\\MyNamespace\\MyRpc',
            $router->testUriToQualifiedName('/remote/MyApp/MyNamespace/MyRpc')
        );
    }

    /**
     * @covers app\decibel\router\DRpcRouter::getErrorMessage
     */
    public function testgetErrorMessage()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $router = TestRpcRouter::load();
        $this->assertLabel($router->testGetErrorMessage('app\\decibel\\InvalidRpc'), 'errorInvalidRpc',
                           DRpcRouter::class);
    }

    /**
     * @covers app\decibel\router\DRpcRouter::getPriority
     */
    public function testgetPriority()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $router = TestRpcRouter::load();
        $this->assertSame(5, $router->getPriority());
    }

    /**
     * @covers app\decibel\router\DRpcRouter::getPattern
     */
    public function testgetPattern()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $router = TestRpcRouter::load();
        $this->assertSame('/^(remote\/decibel\/rpc\/DHandshake$|remote(\/.+$))/', $router::getPattern());
    }

    /**
     * @covers app\decibel\router\DRpcRouter::profile
     */
    public function testprofile()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $router = TestRpcRouter::load();
        $this->assertFalse($router->profile());
    }
}
