<?php
namespace tests\app\decibel\model\utilisation;

use app\decibel\application\DApp;
use app\decibel\configuration\DApplicationMode;
use app\decibel\model\utilisation\DRebuildUtilisationIndex;
use app\decibel\test\DTestCase;

/**
 * Test class for DRebuildUtilisationIndex.
 * Generated by Decibel on 2011-10-31 at 14:20:32.
 */
class DRebuildUtilisationIndexTest extends DTestCase
{
    /**
     * @covers app\decibel\model\utilisation\DRebuildUtilisationIndex::canRunInMode
     */
    public function testcanRunInDebugMode()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $task = new DRebuildUtilisationIndex();
        $this->assertTrue($task->canRunInMode(DApplicationMode::MODE_DEBUG));
    }

    /**
     * @covers app\decibel\model\utilisation\DRebuildUtilisationIndex::canRunInMode
     */
    public function testCanRunInTestMode()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
        $task = new DRebuildUtilisationIndex();
        $this->assertTrue($task->canRunInMode(DApplicationMode::MODE_TEST));
    }
}
