<?php
namespace tests\app\decibel\stream;

use app\decibel\stream\DOutputStream;
use app\decibel\test\DTestCase;

/**
 * Test class for DOutputStream.
 * Generated by Decibel on 2011-10-31 at 14:12:32.
 */
class DOutputStreamTest extends DTestCase
{
    /**
     * @covers app\decibel\stream\DOutputStream::__construct
     * @covers app\decibel\stream\DOutputStream::write
     */
    public function test__construct()
    {
        ob_start();
        $stream = new DOutputStream();
        $stream->write('test');
        $this->assertSame('test', ob_get_clean());
    }
}
