<?php
namespace tests\app\decibel\stream;

use app\decibel\stream\DReadableStream;
use app\decibel\test\DTestCase;

class TestReadableStream implements DReadableStream
{
    public function read($length = null)
    {
    }

    public function readLine()
    {
    }
}

/**
 * Test class for DReadableStream.
 * Generated by Decibel on 2011-10-31 at 14:12:32.
 */
class DReadableStreamTest extends DTestCase
{
    /**
     * @covers app\decibel\stream\DReadableStream
     */
    public function test__construct()
    {
        $stream = new TestReadableStream();
        $this->assertInstanceOf('app\\decibel\\stream\\DReadableStream', $stream);
    }
}
