<?php
namespace tests\app\decibel\stream;

use app\decibel\stream\DReadableCsvStream;
use app\decibel\test\DTestCase;

class TestReadableCsvStream implements DReadableCsvStream
{
    public function read($length = null)
    {
    }

    public function readCsvLine($delimiter = ',', $enclosure = '"', $escape = '\\')
    {
    }

    public function readLine()
    {
    }
}

/**
 * Test class for DReadableCsvStream.
 * Generated by Decibel on 2011-10-31 at 14:12:32.
 */
class DReadableCsvStreamTest extends DTestCase
{
    /**
     * @covers app\decibel\stream\DReadableCsvStream
     */
    public function test__construct()
    {
        $stream = new TestReadableCsvStream();
        $this->assertInstanceOf('app\\decibel\\stream\\DReadableCsvStream', $stream);
    }
}
