<?php
namespace tests\app\decibel\stream;

use app\decibel\stream\DWritableStream;
use app\decibel\test\DTestCase;

class TestWritableStream implements DWritableStream
{
    public function erase()
    {
    }

    public function write($data)
    {
    }
}

/**
 * Test class for DWritableStream.
 * Generated by Decibel on 2011-10-31 at 14:12:32.
 */
class DWritableStreamTest extends DTestCase
{
    /**
     * @covers app\decibel\stream\DWritableStream
     */
    public function test__construct()
    {
        $stream = new TestWritableStream();
        $this->assertInstanceOf('app\\decibel\\stream\\DWritableStream', $stream);
    }
}
