<?php
namespace tests\app\decibel\model\index;

use app\decibel\model\field\DTextField;
use app\decibel\model\index\DPrimaryIndex;
use app\decibel\test\DTestCase;

/**
 * Test class for DPrimaryIndex.
 * Generated by Decibel on 2012-04-12 at 09:08:49.
 */
class DPrimaryIndexTest extends DTestCase
{
    /**
     * @covers app\decibel\model\index\DPrimaryIndex::__construct
     */
    public function test__construct()
    {
        $index = new DPrimaryIndex('Primary');
        $this->assertInstanceOf('app\\decibel\\model\\index\\DPrimaryIndex', $index);
        $this->assertSame('PRIMARY', $index->getName());
        $this->assertSame('Primary', $index->getDisplayName());
    }

    /**
     * @covers app\decibel\model\index\DPrimaryIndex::addField
     */
    public function testaddField()
    {
        $index = new DPrimaryIndex('Primary');
        $field = new DTextField('test', 'Test');
        $this->assertSame($index, $index->addField($field));
    }

    /**
     * @covers app\decibel\model\index\DPrimaryIndex::addField
     * @expectedException app\decibel\model\index\DInvalidIndexFieldException
     */
    public function testaddField_invalid()
    {
        $index = new DPrimaryIndex('Primary');
        $field = new DTextField('test', 'Test');
        $field->setNullOption('Null');
        $index->addField($field);
    }

    /**
     * @covers app\decibel\model\index\DPrimaryIndex::getDatabaseIdentifier
     */
    public function testgetDatabaseIdentifier()
    {
        $index = new DPrimaryIndex('Primary');
        $this->assertSame('PRIMARY', $index->getDatabaseIdentifier());
    }
}
