<?php
namespace tests\app\decibel\model\index;

use app\decibel\model\index\DUniqueIndex;
use app\decibel\test\DTestCase;

/**
 * Test class for DUniqueIndex.
 * Generated by Decibel on 2012-04-12 at 09:08:49.
 */
class DUniqueIndexTest extends DTestCase
{
    /**
     * @covers app\decibel\model\index\DUniqueIndex::getDatabaseIdentifier
     */
    public function testgetDatabaseIdentifier()
    {
        $index = new DUniqueIndex('unique');
        $this->assertSame('UNIQUE', $index->getDatabaseIdentifier());
    }
}
