<?php
namespace tests\app\decibel\model\field;

use app\decibel\model\field\DField;
use app\decibel\model\field\DFloatField;
use app\decibel\test\DTestCase;

/**
 * Test class for DFloatField.
 * Generated by Decibel on 2012-04-12 at 09:08:41.
 */
class DFloatFieldTest extends DTestCase
{
    /**
     * @covers app\decibel\model\field\DFloatField::getDataType
     */
    public function testgetDataType()
    {
        $field = new DFloatField('test', 'Test');
        $this->assertSame(DField::DATA_TYPE_FLOAT, $field->getDataType());
    }

    /**
     * @covers app\decibel\model\field\DFloatField::getInternalDataType
     */
    public function testgetInternalDataType()
    {
        $field = new DFloatField('test', 'Test');
        $this->assertSame('double', $field->getInternalDataType());
    }

    /**
     * @covers app\decibel\model\field\DFloatField::setDefaultOptions
     */
    public function testsetDefaultOptions()
    {
        $field = new DFloatField('test', 'Test');
        $this->assertFalse($field->unsigned);
    }

    /**
     * @covers app\decibel\model\field\DFloatField::setPrecision
     */
    public function testsetPrecision()
    {
        $field = new DFloatField('test', 'Test');
        $this->assertSame($field, $field->setPrecision(10));
        $this->assertSame(10, $field->getPrecision());
    }

    /**
     * @covers app\decibel\model\field\DFloatField::setPrecision
     * @expectedException app\decibel\debug\DInvalidParameterValueException
     */
    public function testsetPrecision_invalid()
    {
        $field = new DFloatField('test', 'Test');
        $field->setPrecision('100');
    }

    /**
     * @covers app\decibel\model\field\DFloatField::setSize
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testsetSize()
    {
        $field = new DFloatField('test', 'Test');
        $field->setSize(1);
    }

    /**
     * @covers app\decibel\model\field\DFloatField::setUnsigned
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testsetUnsigned()
    {
        $field = new DFloatField('test', 'Test');
        $field->setUnsigned(true);
    }
}
