<?php
namespace tests\app\decibel\model\field;

use app\decibel\model\field\DField;
use app\decibel\model\field\DIdField;
use app\decibel\test\DTestCase;

/**
 * Test class for DIdField.
 * Generated by Decibel on 2012-04-12 at 09:08:41.
 */
class DIdFieldTest extends DTestCase
{
    /**
     * @covers app\decibel\model\field\DIdField::getStandardDefaultValue
     */
    public function testGetStandardDefaultValue()
    {
        $field = new DIdField('test', 'Test');
        $this->assertNull($field->getDefaultValue());
    }

    /**
     * @covers app\decibel\model\field\DIdField::setDefaultOptions
     */
    public function testSetDefaultOptions()
    {
        $field = new DIdField('test', 'Test');
        $this->assertFalse($field->isExportable());
        $this->assertFalse($field->randomisable);
        $this->assertTrue($field->readOnly);
        $this->assertSame(DIdField::SIZE, $field->size);
        $this->assertTrue($field->unsigned);
    }

    /**
     * @covers app\decibel\model\field\DIdField::setExportable
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testSetExportable()
    {
        $field = new DIdField('test', 'Test');
        $field->setExportable(true);
    }

    /**
     * @covers app\decibel\model\field\DIdField::setRandomisable
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testSetRandomisable()
    {
        $field = new DIdField('test', 'Test');
        $field->setRandomisable(true);
    }

    /**
     * @covers app\decibel\model\field\DIdField::setReadOnly
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testSetReadOnly()
    {
        $field = new DIdField('test', 'Test');
        $field->setReadOnly(true);
    }

    /**
     * @covers app\decibel\model\field\DIdField::setSize
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testSetSize()
    {
        $field = new DIdField('test', 'Test');
        $field->setSize(1);
    }

    /**
     * @covers app\decibel\model\field\DIdField::setUnsigned
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testSetUnsigned()
    {
        $field = new DIdField('test', 'Test');
        $field->setUnsigned(true);
    }
}
