<?php
namespace tests\app\decibel\model\field;

use app\decibel\model\field\DLanguageField;
use app\decibel\regional\DLanguage;
use app\decibel\test\DTestCase;

/**
 * Test class for DLanguageField.
 * Generated by Decibel on 2012-04-12 at 09:08:41.
 */
class DLanguageFieldTest extends DTestCase
{
    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     */
    public function testCastValueNull()
    {
        $field = new DLanguageField('test', 'Test');
        $field->setNullOption('Null');
        $this->assertNull($field->castValue(null));
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     */
    public function testCastValueNullInvalid()
    {
        $field = new DLanguageField('test', 'Test');
        $this->assertNull($field->castValue(null));
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     */
    public function testCastValueString()
    {
        $field = new DLanguageField('test', 'Test');
        $this->assertSame('en', $field->castValue('en'));
        $this->assertSame('es', $field->castValue('es'));
        $this->assertSame('en-au', $field->castValue('en-au'));
        $this->assertSame('es-co', $field->castValue('es-co'));
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     */
    public function testCastValueDLanguage()
    {
        $field = new DLanguageField('test', 'Test');
        $language = new DLanguage('en', 'English', 'English', 'au');
        $this->assertSame('en', $field->castValue($language));
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     * @expectedException app\decibel\model\debug\DInvalidFieldValueException
     */
    public function testCastValueStringInvalid1()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->castValue('e');
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     * @expectedException app\decibel\model\debug\DInvalidFieldValueException
     */
    public function testCastValueStringInvalid2()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->castValue('eng');
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     * @expectedException app\decibel\model\debug\DInvalidFieldValueException
     */
    public function testCastValueStringInvalid3()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->castValue('en-');
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     * @expectedException app\decibel\model\debug\DInvalidFieldValueException
     */
    public function testCastValueStringInvalid4()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->castValue('en-a');
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     * @expectedException app\decibel\model\debug\DInvalidFieldValueException
     */
    public function testCastValueStringInvalid5()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->castValue('en-aus');
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::castValue
     * @expectedException app\decibel\model\debug\DInvalidFieldValueException
     */
    public function testCastValueStringInvalid6()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->castValue('3n-au');
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::setCharLimit
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testSetCharLimit()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->setCharLimit('');
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::setDefaultOptions
     */
    public function testSetDefaultOptions()
    {
        $field = new DLanguageField('test', 'Test');
        $this->assertSame(5, $field->maxLength);
        $this->assertSame('abcdefghijklmnopqrstuvwxyz-', $field->charLimit);
    }

    /**
     * @covers app\decibel\model\field\DLanguageField::setMaxLength
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testSetMaxLength()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new DLanguageField('test', 'Test');
        $field->setMaxLength(1);
    }
}
