<?php
namespace tests\app\decibel\model\field;

use app\decibel\authorise\DGroup;
use app\decibel\model\field\DField;
use app\decibel\model\field\DOneToOneRelationalField;
use app\decibel\test\DTestCase;

class TestOneToOneRelationalField extends DOneToOneRelationalField
{
}

/**
 * Test class for DOneToOneRelationalField.
 * Generated by Decibel on 2012-04-12 at 09:08:41.
 */
class DOneToOneRelationalFieldTest extends DTestCase
{
    /**
     * @covers app\decibel\model\field\DOneToOneRelationalField::getDataType
     */
    public function testGetDataType()
    {
        $field = new TestOneToOneRelationalField('test', 'Test');
        $this->assertSame(DField::DATA_TYPE_BIGINT, $field->getDataType());
    }

    /**
     * @covers app\decibel\model\field\DOneToOneRelationalField::getDefinition
     */
    public function testGetDefinition()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new TestOneToOneRelationalField('test', 'Test');
        $field->setNullOption(null);
        $definition = $field->getDefinition();
        $this->assertTrue($definition->unsigned);
        $this->assertTrue($definition->null);
    }

    /**
     * @covers app\decibel\model\field\DOneToOneRelationalField::getDefinition
     */
    public function testGetDefinitionRequired()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new TestOneToOneRelationalField('test', 'Test');
        $field->setNullOption(null);
        $field->setRequired(true);
        $definition = $field->getDefinition();
        $this->assertTrue($definition->unsigned);
        $this->assertFalse($definition->null);
    }

    /**
     * @covers app\decibel\model\field\DOneToOneRelationalField::getDefinition
     */
    public function testGetDefinitionNull()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $field = new TestOneToOneRelationalField('test', 'Test');
        $field->setNullOption('Null');
        $definition = $field->getDefinition();
        $this->assertTrue($definition->unsigned);
        $this->assertTrue($definition->null);
    }

    /**
     * @covers app\decibel\model\field\DOneToOneRelationalField::getInternalDataType
     */
    public function testGetInternalDataType()
    {
        $field = new TestOneToOneRelationalField('test', 'Test');
        $this->assertSame('object', $field->getInternalDataType());
        $field->setLinkTo(DGroup::class);
        $this->assertSame(
            DGroup::class,
            $field->getInternalDataType()
        );
    }
}
