<?php
namespace tests\app\decibel\reflection;

use app\decibel\reflection\DReflectable;
use app\decibel\test\DTestCase;

class TestReflectable implements DReflectable
{
    public static function getDescription()
    {
    }

    public static function getDisplayName()
    {
    }

    public static function getReflection()
    {
    }
}

/**
 * Test class for DReflectable.
 * Generated by Decibel on 2012-04-12 at 09:07:35.
 */
class DReflectableTest extends DTestCase
{
    /**
     * @covers app\decibel\reflection\DReflectable
     */
    public function test__construct()
    {
        $stream = new TestReflectable();
        $this->assertInstanceOf('app\\decibel\\reflection\\DReflectable', $stream);
    }
}
