<?php
namespace tests\app\decibel\database\mysql\mapper;

use app\decibel\database\mysql\mapper\DMySQLColumnSchemaMapper;
use app\decibel\database\schema\DColumnDefinition;
use app\decibel\test\DTestCase;

if (!class_exists('TestDColumnDefinition')) {
    class TestDColumnDefinition extends DColumnDefinition
    {
        public function testcompareNames($a, $b)
        {
            return static::compareNames($a, $b);
        }
    }
}

/**
 * Test class for DMySQLColumnSchemaMapper.
 * Generated by Decibel on 2011-10-31 at 14:07:42.
 */
class DMySQLColumnSchemaMapperTest extends DTestCase
{
    /**
     * @var DMySQLColumnSchemaMapper
     */
    protected $definition;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->definition = new DMySQLColumnSchemaMapper('testing');
    }

    /**
     * @covers app\decibel\database\mysql\mapper\DMySQLColumnSchemaMapper::getCreateSql
     */
    public function testgetCreateSql()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $result = $this->definition->getCreateSql();
        $this->assertinternalType('string', $result);
        $this->assertSame('`testing`  not null', $result);
    }
}
