<?php
namespace tests\app\decibel\cache\utility;

use app\decibel\cache\utility\DCacheHealthCheck;
use app\decibel\health\DHealthCheckResult;
use app\decibel\test\DTestCase;

/**
 * Test class for DCacheHealthCheck.
 * Generated by Decibel on 2011-10-31 at 14:07:11.
 */
class DCacheHealthCheckTest extends DTestCase
{
    /**
     * @covers app\decibel\cache\utility\DCacheHealthCheck::load
     */
    public function testCreate()
    {
        $this->assertInstanceOf(DCacheHealthCheck::class, DCacheHealthCheck::load());
    }

    /**
     * @covers app\decibel\cache\utility\DCacheHealthCheck::getComponentName
     */
    public function testGetComponentName()
    {
        $healthCheck = DCacheHealthCheck::load();
        $this->assertLabel($healthCheck->getComponentName(), 'componentName', DCacheHealthCheck::class);
    }

    /**
     * @covers app\decibel\cache\utility\DCacheHealthCheck::checkHealth
     */
    public function testCheckHealth()
    {
        $healthCheck = DCacheHealthCheck::load();
        $results = $healthCheck->checkHealth();

        $this->assertContainsOnlyInstancesOf(DHealthCheckResult::class, $results);
    }
}
