<?php
namespace tests\app\decibel\cache;

use app\decibel\cache\DCapabilityCache;
use app\decibel\test\DTestCase;

/**
 * Test class for DCapabilityCache.
 * Generated by Decibel on 2011-10-31 at 14:07:03.
 */
class DCapabilityCacheTest extends DTestCase
{
    /**
     * @covers app\decibel\cache\DCapabilityCache::clear
     */
    public function testClear()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\cache\DCapabilityCache::clearUser
     */
    public function testClearUser()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\cache\DCapabilityCache::getForUser
     */
    public function testGetForUser()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\cache\DCapabilityCache::setForUser
     */
    public function testSetForUser()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
