<?php
namespace tests\app\decibel\model\database;

use app\decibel\model\database\DLightModelDatabaseMapper;
use app\decibel\model\DLightModel;
use app\decibel\test\DTestCase;

/**
 * Test class for DLightModelDatabaseMapper.
 * Generated by Decibel on 2012-04-12 at 09:08:49.
 */
class DLightModelDatabaseMapperTest extends DTestCase
{
    /**
     * @covers app\decibel\model\database\DLightModelDatabaseMapper::getDecoratedClass
     */
    public function testgetDecoratedClass()
    {
        $this->assertSame(DLightModel::class, DLightModelDatabaseMapper::getDecoratedClass());
    }
}
