<?php
namespace tests\app\decibel\model\event;

use app\decibel\model\event\DOnBeforeDelete;
use app\decibel\test\DTestCase;

/**
 * Test class for DOnBeforeDelete.
 * Generated by Decibel on 2012-04-12 at 09:08:49.
 */
class DOnBeforeDeleteTest extends DTestCase
{
    /**
     * @covers app\decibel\model\event\DOnBeforeDelete
     */
    public function test__construct()
    {
        $event = new DOnBeforeDelete();
        $this->assertInstanceOf('app\\decibel\\model\\event\\DOnBeforeDelete', $event);
    }
}
