<?php
namespace tests\app\decibel\model\event;

use app\decibel\model\event\DOnDelete;
use app\decibel\test\DTestCase;

/**
 * Test class for DOnDelete.
 * Generated by Decibel on 2012-04-12 at 09:08:49.
 */
class DOnDeleteTest extends DTestCase
{
    /**
     * @covers app\decibel\model\event\DOnDelete
     */
    public function test__construct()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $event = new DOnDelete();
        $this->assertInstanceOf('app\\decibel\\model\\event\\DOnDelete', $event);
    }
}
