<?php
namespace tests\app\decibel\model\event;

use app\decibel\model\event\DOnUncache;
use app\decibel\test\DTestCase;

/**
 * Test class for DOnUncache.
 * Generated by Decibel on 2012-04-12 at 09:08:49.
 */
class DOnUncacheTest extends DTestCase
{
    /**
     * @covers app\decibel\model\event\DOnUncache
     */
    public function test__construct()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $event = new DOnUncache();
        $this->assertInstanceOf('app\\decibel\\model\\event\\DOnUncache', $event);
    }
}
