<?php
namespace tests\app\decibel\database\mysql;

use app\decibel\database\DDatabase;
use app\decibel\database\DDatabaseInformation;
use app\decibel\database\mysql\DMySQLInformation;
use app\decibel\database\schema\DColumnDefinition;
use app\decibel\test\DTestCase;

/**
 * Test class for DMySQL.
 * Generated by Decibel on 2011-10-31 at 14:08:15.
 */
class DMySQLInformationTest extends DTestCase
{
    /**
     * @covers app\decibel\database\mysql\DMySQLInformation::getTableColumn
     */
    public function testgetTableColumn()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $row = array(
            'Default' => '',
            'Field'   => 'Testing',
            'Extra'   => '',
            'Null'    => '',
            'Type'    => '',
        );
        $database = DDatabase::getDatabase();
        $mysqlInformation = DDatabaseInformation::adapt($database);
        $result = $this->executeMethod($mysqlInformation, 'getTableColumn', array($row));
        $this->assertInstanceOf(DColumnDefinition::class, $result);
        $this->assertSame('Testing', $result->name);
        $this->assertNull($result->type);
        $this->assertNull($result->size);
        $this->assertFalse($result->null);
        $this->assertFalse($result->unsigned);
    }
}
