<?php
namespace tests\app\decibel\registry;

use app\decibel\registry\DOnGlobalHiveUpdate;
use app\decibel\test\DTestCase;
use PHPUnit_Framework_TestCase;

/**
 * Test class for DOnGlobalHiveUpdate.
 * Generated by Decibel on 2011-10-31 at 14:12:38.
 */
class DOnGlobalHiveUpdateTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers app\decibel\registry\DOnGlobalHiveUpdate::getDescription
     */
    public function testgetDescription()
    {
        $event = new DOnGlobalHiveUpdate();
        $this->assertNull($event->getDescription());
    }

    /**
     * @covers app\decibel\registry\DOnGlobalHiveUpdate::getDisplayName
     */
    public function testgetDisplayName()
    {
        $event = new DOnGlobalHiveUpdate();
        $this->assertNull($event->getDisplayName());
    }
}
