<?php
namespace tests\app\decibel\security;

use app\decibel\security\DPciSecurityPolicy;
use app\decibel\security\DSecurityPolicy;
use app\decibel\test\DTestCase;

/**
 * Test class for DPciSecurityPolicy.
 * Generated by Decibel on 2012-04-12 at 09:06:03.
 */
class DPciSecurityPolicyTest extends DTestCase
{
    /**
     * @covers app\decibel\security\DPciSecurityPolicy::initialise
     */
    public function test__wakeup()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = unserialize('O:42:"app\decibel\security\DPciSecurityPolicy":0:{}');
        $this->assertSame(DSecurityPolicy::AUTH_FACTORS_TWO, $policy->getFieldValue('authFactorRequirement'));
        $this->assertSame(6, $policy->getFieldValue('failedLoginLockout'));
        $this->assertSame(90, $policy->getFieldValue('inactiveLockout'));
        $this->assertSame(30, $policy->getFieldValue('lockoutLength'));
        $this->assertSame(1, $policy->getFieldValue('sessionLimit'));
        $this->assertSame(8, $policy->getFieldValue('minimumPasswordLength'));
        $this->assertSame(DSecurityPolicy::OVERRIDE_STRONGER, $policy->getFieldValue('overrideCondition'));
        $this->assertSame(90, $policy->getFieldValue('passwordLife'));
        $this->assertSame(DSecurityPolicy::PASSWORD_STRENGTH_MEDIUM, $policy->getFieldValue('passwordStrength'));
        $this->assertSame(5, $policy->getFieldValue('rememberedPasswords'));
        $this->assertSame(15, $policy->getFieldValue('sessionTimeout'));
    }

    /**
     * @covers app\decibel\security\DPciSecurityPolicy::__construct
     * @covers app\decibel\security\DPciSecurityPolicy::initialise
     */
    public function test__construct()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new DPciSecurityPolicy();
        $this->assertSame(DSecurityPolicy::AUTH_FACTORS_TWO, $policy->getFieldValue('authFactorRequirement'));
        $this->assertSame(6, $policy->getFieldValue('failedLoginLockout'));
        $this->assertSame(90, $policy->getFieldValue('inactiveLockout'));
        $this->assertSame(30, $policy->getFieldValue('lockoutLength'));
        $this->assertSame(1, $policy->getFieldValue('sessionLimit'));
        $this->assertSame(8, $policy->getFieldValue('minimumPasswordLength'));
        $this->assertSame(DSecurityPolicy::OVERRIDE_STRONGER, $policy->getFieldValue('overrideCondition'));
        $this->assertSame(90, $policy->getFieldValue('passwordLife'));
        $this->assertSame(DSecurityPolicy::PASSWORD_STRENGTH_MEDIUM, $policy->getFieldValue('passwordStrength'));
        $this->assertSame(5, $policy->getFieldValue('rememberedPasswords'));
        $this->assertSame(15, $policy->getFieldValue('sessionTimeout'));
    }

    /**
     * @covers app\decibel\security\DPciSecurityPolicy::__set
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function test__set()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new DPciSecurityPolicy();
        $policy->test = 'test';
    }

    /**
     * @covers app\decibel\security\DPciSecurityPolicy::getDescription
     */
    public function testgetDescription()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new DPciSecurityPolicy();
        $this->assertLabel($policy->getDescription(), 'description', 'app\\decibel\\security\\DPciSecurityPolicy');
    }

    /**
     * @covers app\decibel\security\DPciSecurityPolicy::getName
     */
    public function testgetName()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new DPciSecurityPolicy();
        $this->assertLabel($policy->getName(), 'name', 'app\\decibel\\security\\DPciSecurityPolicy');
    }

    /**
     * @covers app\decibel\security\DPciSecurityPolicy::isConfigurable
     */
    public function testisConfigurable()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new DPciSecurityPolicy();
        $this->assertFalse($policy->isConfigurable());
    }

    /**
     * @covers app\decibel\security\DPciSecurityPolicy::setFieldValue
     * @expectedException app\decibel\debug\DReadOnlyParameterException
     */
    public function testsetFieldValue()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new DPciSecurityPolicy();
        $policy->setFieldValue('test', 'test');
    }
}
