<?php
namespace tests\app\decibel\security;

use app\decibel\security\DSecurityPolicy;
use app\decibel\test\DTestCase;

class TestSecurityPolicy extends DSecurityPolicy
{
    public function getDescription()
    {
    }

    public function getName()
    {
    }

    protected function initialise()
    {
    }
}

/**
 * Test class for DSecurityPolicy.
 * Generated by Decibel on 2012-04-12 at 09:06:10.
 */
class DSecurityPolicyTest extends DTestCase
{
    public function setUp()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\security\DSecurityPolicy::__construct
     * @covers app\decibel\security\DSecurityPolicy::define
     */
    public function test__construct()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new TestSecurityPolicy();
        $this->assertInstanceOf(DSecurityPolicy::class, $policy);
        $this->assertSame(DSecurityPolicy::OVERRIDE_STRONGER, $policy->getOverrideCondition());
    }

    /**
     * @covers app\decibel\security\DSecurityPolicy::getOverrideCondition
     * @covers app\decibel\security\DSecurityPolicy::setOverrideCondition
     */
    public function testgetOverrideCondition()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new TestSecurityPolicy();
        $this->assertSame($policy, $policy->setOverrideCondition(DSecurityPolicy::OVERRIDE_WEAKER));
        $this->assertSame(DSecurityPolicy::OVERRIDE_WEAKER, $policy->getOverrideCondition());
    }

    /**
     * @covers app\decibel\security\DSecurityPolicy::setOverrideCondition
     * @expectedException app\decibel\model\debug\DInvalidFieldValueException
     */
    public function testgetOverrideCondition_invalid()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

        $policy = new TestSecurityPolicy();
        $policy->setOverrideCondition(100);
    }

    /**
     * @covers app\decibel\security\DSecurityPolicy::generateRandomPassword
     * @todo   Implement testGenerateRandomPassword().
     */
    public function testgenerateRandomPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\security\DSecurityPolicy::isConfigurable
     * @todo   Implement testIsConfigurable().
     */
    public function testisConfigurable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\security\DSecurityPolicy::isStrongerThan
     * @todo   Implement testIsStrongerThan().
     */
    public function testisStrongerThan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers app\decibel\security\DSecurityPolicy::testPassword
     * @todo   Implement testTestPassword().
     */
    public function testtestPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
